language: ruby
rvm:
- 2.2
#- 2.1
#- 2.0
- 1.9.3
env:
- DOCKER_IMAGES=ubuntu:14.04 ANSIBLE_VERSIONS=1.4.4
- DOCKER_IMAGES=ubuntu:14.04 ANSIBLE_VERSIONS=1.5.4
- DOCKER_IMAGES=ubuntu:14.04 ANSIBLE_VERSIONS=1.7.2
- DOCKER_IMAGES=ubuntu:14.04 ANSIBLE_VERSIONS=1.8.4
- DOCKER_IMAGES=ubuntu:14.04 ANSIBLE_VERSIONS=1.9.2
- DOCKER_IMAGES=ubuntu:14.04 ANSIBLE_VERSIONS=2.0.0.2
- DOCKER_IMAGES=ubuntu:14.04 ANSIBLE_VERSIONS=2.1.0.0
- DOCKER_IMAGES=ubuntu:14.04 ANSIBLE_VERSIONS=2.5.1
- DOCKER_IMAGES=ubuntu:16.04 ANSIBLE_VERSIONS=1.4.4
- DOCKER_IMAGES=ubuntu:16.04 ANSIBLE_VERSIONS=1.5.4
- DOCKER_IMAGES=ubuntu:16.04 ANSIBLE_VERSIONS=1.7.2
- DOCKER_IMAGES=ubuntu:16.04 ANSIBLE_VERSIONS=1.8.4
- DOCKER_IMAGES=ubuntu:16.04 ANSIBLE_VERSIONS=1.9.2
- DOCKER_IMAGES=ubuntu:16.04 ANSIBLE_VERSIONS=2.0.0.2
- DOCKER_IMAGES=ubuntu:16.04 ANSIBLE_VERSIONS=2.1.0.0
- DOCKER_IMAGES=ubuntu:16.04 ANSIBLE_VERSIONS=2.5.1
- DOCKER_IMAGES=fedora:20 ANSIBLE_VERSIONS=1.4.4
- DOCKER_IMAGES=fedora:20 ANSIBLE_VERSIONS=1.5.4
- DOCKER_IMAGES=fedora:20 ANSIBLE_VERSIONS=1.7.2
- DOCKER_IMAGES=fedora:20 ANSIBLE_VERSIONS=1.8.4
- DOCKER_IMAGES=fedora:20 ANSIBLE_VERSIONS=1.9.2
- DOCKER_IMAGES=fedora:20 ANSIBLE_VERSIONS=2.0.0.2
- DOCKER_IMAGES=fedora:20 ANSIBLE_VERSIONS=2.1.0.0
- DOCKER_IMAGES=fedora:20 ANSIBLE_VERSIONS=2.5.1
- DOCKER_IMAGES=fedora:25 ANSIBLE_VERSIONS=1.4.4
- DOCKER_IMAGES=fedora:25 ANSIBLE_VERSIONS=1.5.4
- DOCKER_IMAGES=fedora:25 ANSIBLE_VERSIONS=1.7.2
- DOCKER_IMAGES=fedora:25 ANSIBLE_VERSIONS=1.8.4
- DOCKER_IMAGES=fedora:25 ANSIBLE_VERSIONS=1.9.2
- DOCKER_IMAGES=fedora:25 ANSIBLE_VERSIONS=2.0.0.2
- DOCKER_IMAGES=fedora:25 ANSIBLE_VERSIONS=2.1.0.0
- DOCKER_IMAGES=fedora:25 ANSIBLE_VERSIONS=2.5.1
- DOCKER_IMAGES=debian:8 ANSIBLE_VERSIONS=1.4.4
- DOCKER_IMAGES=debian:8 ANSIBLE_VERSIONS=1.5.4
- DOCKER_IMAGES=debian:8 ANSIBLE_VERSIONS=1.7.2
- DOCKER_IMAGES=debian:8 ANSIBLE_VERSIONS=1.8.4
- DOCKER_IMAGES=debian:8 ANSIBLE_VERSIONS=1.9.2
- DOCKER_IMAGES=debian:8 ANSIBLE_VERSIONS=2.0.0.2
- DOCKER_IMAGES=debian:8 ANSIBLE_VERSIONS=2.1.0.0
- DOCKER_IMAGES=debian:8 ANSIBLE_VERSIONS=2.5.1
services:
- docker
script:
- wget -qO- bit.ly/ansibletest | sh
after_failure:
- cat role-tester-ansible-master/.kitchen/logs/*.log | grep -v '^I, '
notifications:
  webhooks: https://galaxy.ansible.com/api/v1/notifications/
  slack:
    on_success: change
    on_failure: change
    rooms:
      - secure: lroFi5YGf0vHa3KvTj8TZF6Z/srlGEmnIBfeKiJsyHO8Z52g56csfpZBYpluPjc8LRB+C7l1DNxf9jxtuBiLZy1P7tF4mXAieH3G8SgP2jTjRuABHNfUX6tJQkbuqz/4QS41EctNP0aFB4/IxksT+rNccayHanRUHqOcK6jrb+8joNnHieAm7YCnPRkfTf2drIbJBRJbtlZ9dihbxQLWH/jD9GKgm5cX/6js4syo3dTutIN3uFEz5t+v4cqUc0x8VqyOrq8n1hGYFR8G4kC7LiohFlAq5QBNM971VFqtAQkD54ZSxv8ZhmV6AMpfF6ULGsWX0Re+idYtnp2vorRETz3bLnExHCAA4U2tPqUodq7K7hkZ8wbKbjPo0okremhJdV8La3NbsM3ZTZcy0/pseApI8+dsUqNey5qDY2ZbGajYyscsNahzCgIBZaszHxe/aT9kIQr3523q0SmomwZ7zS5YrehQFnJtKqm0YrjtM/c/mL0c/5Il8b8A2CyjRek12mnQCjf/P7qGmh00WIFSpNk2KrEjQxrwoK7XJw09vDD37LTzXSO47aeISbKnBjF0KhFy3HCYeRzYrWf7+ZrbDPVoMi/e5uPOIRsKsrIHGNpxhysUQ8h1j6JRcxDk79zUrzV2HIv8PvglZ7GZzVG3GQomd6ixGIozJv79x3BkA1U=
  email:
    recipients:
      secure: n4k3T0i6iObAyUAZW63EliM3vGbIDqYOVWMu9v1CGeKw4N3phZcGbZspc7prEdpDB0coh6CT5kp+eru8t/l6ov2NvNbriAKcvgTsmpzR5ypRazPz1r3y5LPHMulcLWgMPkifLkmxS9f3YlDF8+g33TtiJvHuY0V2EgCafSMCIQSBBsYtBEj5vXSJ4ARdEi/rbj+wRpbkWKvBRo48gOePoFeTKb916G3GsGbrVi27dZPmNgVgcJxAlxl9TnCd9iI6Qm0xJ9MogonH0ndmy9oRO9+N54QpcGgic8dMpj61/0D2173gF8M8MPGlhHfi0FEVeQ8RFSpeUEf6GY4UU/UkC3zUmMNVQKvJ1522bdP4rNkQv4irhgxYGLMNDV0QaQNc7L8qSRjZ9wBjrzxgyvYWAX8IIEGtob1kPUes5RtxM29M2wnvAIg+md8KR0r7EDEdX5uNKEINsuBV35enIDU0P/jpKXRoYcrqa7f/r/MNEwEzOBwHejzMH/+DUkg5htUo9QdEDS4+vwShc+j2Vg2lQdadBeitrrQzKXOMWUvUcjhK5ZLrOHA79yvKgZbi6qNKx1o+COsvpZXstljsu5OWpTRX324tOECZXQo7DWuof6p3AFDZD/+ZtgRDfpQIilG4uP8nR8OcLpdozgXEpoXD6+JFufoGdxwblK/UfaNHFds=
